package Calculator_using_GUI;

public class myframe extends javax.swing.JFrame
{

    private javax.swing.JButton SubBut;
    private javax.swing.JButton addBut;
    private javax.swing.JButton clearBut;
    private javax.swing.JButton exitBut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel opLbl;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;

    public myframe()
    {
        initComponents();
        txt1.setText("");
        txt2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        opLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        addBut = new javax.swing.JButton();
        SubBut = new javax.swing.JButton();
        clearBut = new javax.swing.JButton();
        exitBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 102, 102))); // NOI18N

        opLbl.setText("?");

        jLabel2.setText("=");

        resultLbl.setText("jLabel3");

        txt1.setText("jTextField1");
        txt1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt1ActionPerformed(evt);
            }
        });

        txt2.setText("jTextField2");

        addBut.setForeground(new java.awt.Color(0, 51, 255));
        addBut.setText("+");
        addBut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addButActionPerformed(evt);
            }
        });

        SubBut.setBackground(new java.awt.Color(255, 204, 204));
        SubBut.setForeground(new java.awt.Color(0, 153, 51));
        SubBut.setText("-");
        SubBut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SubButActionPerformed(evt);
            }
        });

        clearBut.setBackground(new java.awt.Color(255, 153, 153));
        clearBut.setForeground(new java.awt.Color(153, 0, 0));
        clearBut.setText("Clear");
        clearBut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearButActionPerformed(evt);
            }
        });

        exitBut.setBackground(new java.awt.Color(255, 153, 153));
        exitBut.setForeground(new java.awt.Color(153, 0, 0));
        exitBut.setText("Exit");
        exitBut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(opLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel2)
                                                .addGap(34, 34, 34)
                                                .addComponent(resultLbl))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addComponent(addBut)
                                                                .addGap(22, 22, 22))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(clearBut)
                                                                .addGap(18, 18, 18)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(exitBut)
                                                        .addComponent(SubBut))))
                                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(opLbl)
                                        .addComponent(jLabel2)
                                        .addComponent(resultLbl)
                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addBut)
                                        .addComponent(SubBut))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clearBut)
                                        .addComponent(exitBut))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void clearButActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_clearButActionPerformed
        resultLbl.setText(" ");
        opLbl.setText(" ? ");
        txt1.setText(" ");
        txt2.setText(" ");
    }//GEN-LAST:event_clearButActionPerformed

    private void addButActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_addButActionPerformed
        int intResult;
        int intNum1;
        int intNum2;

        //Get information from text fields
        intNum1 = Integer.parseInt(txt1.getText());
        intNum2 = Integer.parseInt(txt2.getText());

        //Perform calculations
        intResult = intNum1 + intNum2;

        //Return and display data
        resultLbl.setText(String.valueOf(intResult));
        //Set symbol
        opLbl.setText(" + ");

    }//GEN-LAST:event_addButActionPerformed

    private void SubButActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_SubButActionPerformed
        int intResult;
        int intNum1;
        int intNum2;

        //Get information from text fields
        intNum1 = Integer.parseInt(txt1.getText());
        intNum2 = Integer.parseInt(txt2.getText());

        //Perform calculations
        intResult = intNum1 - intNum2;

        //Return and display data
        resultLbl.setText(String.valueOf(intResult));
        //Set symbol
        opLbl.setText(" - ");

    }//GEN-LAST:event_SubButActionPerformed

    private void exitButActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_exitButActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButActionPerformed

}

// Variables declaration - do not modify//GEN-BEGIN:variables

// End of variables declaration//GEN-END:variables


